<?php

declare(strict_types=1);

namespace App\Filament\Resources\Products\Schemas;

use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

final class ProductInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('group_code')
                    ->placeholder('-'),
                TextEntry::make('product_code')
                    ->placeholder('-'),
                IconEntry::make('is_service')
                    ->boolean()
                    ->placeholder('-'),
                TextEntry::make('name')
                    ->placeholder('-'),
                TextEntry::make('slug'),
                TextEntry::make('catalog_number')
                    ->placeholder('-'),
                TextEntry::make('type')
                    ->placeholder('-'),
                TextEntry::make('size')
                    ->placeholder('-'),
                TextEntry::make('weight')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('rating')
                    ->placeholder('-'),
                TextEntry::make('quality')
                    ->placeholder('-'),
                TextEntry::make('product_variety')
                    ->placeholder('-'),
                TextEntry::make('trade_type')
                    ->placeholder('-'),
                TextEntry::make('usage_type')
                    ->placeholder('-'),
                TextEntry::make('currency_settlement')
                    ->placeholder('-'),
                TextEntry::make('discount_group')
                    ->placeholder('-'),
                IconEntry::make('is_on_sale')
                    ->boolean()
                    ->placeholder('-'),
                TextEntry::make('sale_percentage')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('pricing')
                    ->placeholder('-'),
                TextEntry::make('list_price')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('list_discount')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('purchase_currency_price')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('currency')
                    ->placeholder('-'),
                TextEntry::make('currency_multiplier')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('purchase_price')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('profit_margin')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('net_selling_price')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('vat_class')
                    ->placeholder('-'),
                TextEntry::make('gross_selling_price')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('quantity_unit')
                    ->placeholder('-'),
                TextEntry::make('secondary_unit')
                    ->placeholder('-'),
                TextEntry::make('minimum_stock')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('maximum_stock')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('buffer_stock')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('order_unit')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ksh_prefix')
                    ->placeholder('-'),
                TextEntry::make('ksh_number')
                    ->placeholder('-'),
                TextEntry::make('supplier')
                    ->placeholder('-'),
                TextEntry::make('short_note')
                    ->placeholder('-'),
                TextEntry::make('description')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('barcode')
                    ->placeholder('-'),
                TextEntry::make('ean_code')
                    ->placeholder('-'),
                TextEntry::make('min_order_quantity')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('trade_quantity')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('pallet_quantity')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('custom_fields')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('images')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
            ]);
    }
}
